export const projects = [
  {
    id: "vcloud",
    category: "fullstack",
    stack: ["Django", "Django REST Framework", "React", "React Router", "Redux", "PostgreSQL", "Docker"],
    github: "https://github.com/VikiKuk/VCloud",
    demo: "",
    media: [
      { type: "image", src: "/projects/vcloud/user.png" },
      { type: "image", src: "/projects/vcloud/admin.png" },
      { type: "image", src: "/projects/vcloud/files.png" },
      { type: "image", src: "/projects/vcloud/rename.png" },
      { type: "image", src: "/projects/vcloud/rename2.png" },
      { type: "image", src: "/projects/vcloud/comment.png" },
      { type: "image", src: "/projects/vcloud/share.png" },
      { type: "image", src: "/projects/vcloud/signin.png" },
    ],
  },
  {
    id: "estore",
    category: "fullstack",
    stack: ["React", "React Router", "Redux", "REST API", "LocalStorage", "CSS", "Vite", "Node.js"],
    github: "https://github.com/VikiKuk/E-commerce-store",
    demo: "",
    media: [
      { type: "image", src: "/projects/estore/catalog1.png" },
      { type: "image", src: "/projects/estore/catalog2.png" },
      { type: "image", src: "/projects/estore/product.png" },
      { type: "image", src: "/projects/estore/cart.png" },
      { type: "image", src: "/projects/estore/purchase.png" },
    ],
  },
    {
    id: "helpdesk",
    category: "fullstack",
    stack: ["JavaScript", "Node.js", "Express", "Webpack"],
    github: "https://github.com/VikiKuk/helpdesk-light-version",
    demo: "",
    media: [
      { type: "image", src: "/projects/helpdesc/helpdesk-5.png" },
      { type: "image", src: "/projects/helpdesc/helpdesk-2.png" },
      { type: "image", src: "/projects/helpdesc/helpdesk-3.png" },
      { type: "image", src: "/projects/helpdesc/helpdesk-4.png" },
      { type: "image", src: "/projects/helpdesc/helpdesk.png" },
    ],
  },
  {
    id: "cardvalidator",
    category: "frontend",
    stack: ["JavaScript", "Webpack", "Jest", "Puppeteer"],
    github: "https://github.com/VikiKuk/validating-bank-cards",
    demo: "",
    media: [
      { type: "image", src: "/projects/card-validator/visa correct.png" },
      { type: "image", src: "/projects/card-validator/visa incorrect.png" },
      { type: "image", src: "/projects/card-validator/amex correct.png" },
      { type: "image", src: "/projects/card-validator/noname system.png" },
    ],
  },
  {
    id: "goblingame",
    category: "frontend",
    stack: ["JavaScript", "Webpack", "ESLint"],
    github: "https://github.com/VikiKuk/goblin-game",
    demo: "",
    media: [
      {
        type: "video",
        src: "/projects/goblingame/goblin.mp4",
      },
      { type: "image", src: "/projects/goblingame/loss.png" },
      { type: "image", src: "/projects/goblingame/success.png" },
    ],
  },
  {
    id: "worldclock",
    category: "frontend",
    stack: ["React", "JavaScript", "Vite", "CSS Grid", "Flexbox"],
    github: "https://github.com/VikiKuk/world-clocks",
    demo: "",
    media: [
      { type: "image", src: "/projects/worldclock/clock.png" },
    ],
  },
  {
    id: "kanban",
    category: "frontend",
    stack: ["JavaScript", "CSS", "Webpack", "LocalStorage"],
    github: "https://github.com/VikiKuk/trello-light-version",
    demo: "",
    media: [{ type: "image", src: "/projects/kanban/trello.png" }],
  },
  {
    id: "fileAPI",
    category: "backend",
    stack: ["Django", "Django REST Framework", "PostgreSQL", "Python", "Session Authentication", "RBAC"],
    github: "https://github.com/VikiKuk/RBAC-Backend",
    demo: "",
    media: [{ type: "image", src: "/projects/rbacfile/users.png" }],
  },
];